apiVersion: apps/v1
kind: Deployment
metadata: 
   name: frontend
   labels: 
     web: php-frontend
spec: 
   replicas: 3
   selector: 
      matchLabels: 
         web: php-frontend
   template:
       metadata: 
          labels:
             web: php-frontend
       spec:
          containers:
             - name: my-frontend
               image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5
               env: 
                - name: GET_HOSTS_FROM
                  value: "dns" 
               resources:
                  requests:
                    cpu: "100m"
                    memory: "200Mi"
                  limits: 
                    cpu: "200m"
                    memory: "280Mi"
               ports: 
                   - containerPort: 80    

---

apiVersion: v1
kind: Service
metadata: 
   name: frontend
spec:
   type: ClusterIP
   selector:
      web: php-frontend
   ports:
     - port: 80
       targetPort: 80       

               


