apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis-deploy
  labels:
    app: redis
    role: master
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  template:
    metadata: 
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
        - name: redis-master
          image: "registry.k8s.io/redis@sha256:cb111d1bd870a6a471385a4a69ad17469d326e9dd91e0e455350cacf36e1b3ee"
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "280Mi"
          ports:
            - containerPort: 6379
---
apiVersion: v1  
kind: Service
metadata: 
  name: redis-master-service
spec: 
  type: ClusterIP
  selector:
    app: redis
    role: master
    tier: backend
  ports:
    - port: 6379
      targetPort: 6379
