apiVersion: apps/v1
kind: Deployment
metadata:
   name: redis-follower
   labels:
     app: redis
     role: follower
     tier: backend
spec:
   replicas: 2
   selector: 
      matchLabels: 
         app: redis
         
   template:
      metadata: 
         labels:
           app: redis
           role: follower
           tier: backend
      spec: 
         containers: 
            - name: my-follower
              image: us-docker.pkg.dev/google-samples/containers/gke/gb-redis-follower:v2
              resources: 
                requests: 
                   cpu: "100m"
                   memory: "200Mi"
                limits: 
                   cpu: "200m"
                   memory: "280Mi"
              ports: 
                - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata: 
   name: follower-redis-service
   labels: 
      app: redis
spec: 
   type: ClusterIP
   selector: 
      app: redis
      role: follower
      tier: backend
   ports: 
      - port: 6379
        targetPort: 6379      

